### PR TITLE
Display "kindling" feeds that were not added to a group

### PR DESCRIPTION
**Pull request by flurischt**
Fever displays kindling feeds without a group directly under "Kindling". at the moment Meltdown hides them. this commit displays these items under a new group called "Kindling".

### CODE REVIEW

**Comment by revnode** [comment]
Yeah, this issue is currently stopping me from using Meltdown. I don't group my feeds, so I get nothing. Would be nice if this got accepted.

**Comment by phubbard** [comment]
Sorry, been travelling to PyCon, will try and merge this and cut a release today! Also need to add a bit more code in the mark-group-as-read function to match.

**Comment by phubbard** [comment]
And do let me know if it works or doesn't!

**Comment by revnode** [comment]
Excellent! Just updated on my phone and it works perfectly! Thank you!

**Comment by flurischt** [comment]
looks good to me. the Kindling group and "Mark as read" work as expected. thanks for merging!

@phubbard one more question: did you remove the "sync sparks" preferences because of this issue, what was the reason? I don't need this preference but I think for users with a LOT of high volume sparks this would have been useful.

**Comment by phubbard** [comment]
I did remove it; I need to back up and re-think how I'm dealing with the sparks and kindling supergroups. I'm in demo crunch mode at work, so if you've ideas and want to share them, let me know.

**Comment by MoriTanosuke** [comment]
I added the _sync sparks_ setting exactly for the high volume issue. I had several megabytes of traffic and only a small percentage was from the feeds I actual read.

Maybe there is a better way to solve this with the API of Fever, perhaps selecting which feeds or groups should be synced at all. But the API says:

> The “Kindling” super group is not included in this response and is composed of all feeds with an 
> is_spark equal to 0. The “Sparks” super group is not included in this response and is composed
> of all feeds with an is_spark equal to 1.

So the _kindling_ group is not really a group for fever, mayb that is causing some feeds to vanish when disabling loadin of sparks. But I only check for _is_spark=1_ when checking Sparks... Maybe I can have a look into it as well soon.

**Comment by flurischt** [comment]
> "So the kindling group is not really a group for fever, mayb that is causing some feeds to vanish when disabling loadin of sparks. But I only check for is_spark=1 when checking Sparks..."

that's exactly what I corrected with commit d3f6ac69390b76dab41d00da0a541ec8de746650 the kindling-feeds should no longer vanish. I created the group "Kindling" to display the feeds the same way they are shown on the server. could also have used the "orphan" group. 

In the long term I would propose a hierarchical structure. maybe like this:

=Kindling
==Kindling (opening shows all kindling items including all groups)
==Orphaned Items (kindling items without a group)
==Group1 (opening shows only items of this group)
==Group2

=Sparks
==Sparks (opening shows all spark items)
==Feed1 (opening shows all items of feed1)
==Feed2

I think the Google Reader app has (had?) a similar structure. The advantage would be, that you can fast skip through all items (by opening Kindling/Kindling or Sparks/Sparks) our you can browse just one group/feed. with one more hierarchical level in Kindling #8 could be implemented.

**Pull request merged**
